name: C/C++ CI

on: [push]

jobs:
  build:git clone https://android.googlesource.com/platform/bootable/diskinstaller
  

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
